.TH "DUMPSIG" 1 "May 8, 1990" "Hash Signatures"
.SH NAME
dumpsig - dump a signature in a more-or-less readable format
.SH FOR EXPERIMENTAL USE ONLY

.SH SYNOPSIS
dumpsig file
.SH DESCRIPTION
.B Dumpsig
dumps the signature for the specified file.  Intended primarily for debugging purposes.
.SH EXAMPLES
dumpsig contract
.PP
The signature for file "contract" is printed on standard out.
.SH "SEE ALSO"
check(1) sign(1) destroyoldkey(1) makepublickey(1) recoverauxinfo(1)
.SH AUTHOR
Ralph C. Merkle
Copyright (C) 1990 Xerox Corporation
All Rights Reserved
